### PR TITLE
Bug Fixes and Feature Implementations

### PR DESCRIPTION
**Pull request by tmeneau**
This PR implements the features and bug fixes described in issue #1, including:

* #2 (fix: sensible defaults and defensive property checks)
* #3 (fix: remove unnecessary ensure_namespace states)
* #4 (fix: add accurate change management for configured repos)
* #5 (feat: display helm command executed during release states)
* #6 (feat: persist values as yaml files on the target minion)
* #7 (feat: add module function for packaging charts)
* #8 (feat: split client.sls into distinct state files)
* #9 (chore: ensure module functions are all documented)

Sorry for the large PR, but since most of these changes piggy-back on each other I thought it'd be easier to review the aggregate total of all changes vs. each change individually. Let me know if you have any concerns about any of this, or if there are any changes you'd like me to make prior to feeling comfortable pulling this in. Thanks again for your openness to these contributions!

### CODE REVIEW

**Review by epcim — APPROVED** [review]
I preliminary agreed to merge this.
LG
(please update download_url, avoid hard-coding it without option option to override)

**Comment by tmeneau** [comment]
Thanks for the quick and detailed review, and for including the link to to the salt-formula docs! I'll read up on `reclass` and make an attempt at your requested changes.

**Review by inthuriel — APPROVED** [review]
Looks good for me

**Comment by tmeneau** [comment]
I only realized a couple of days ago that [salt-formulas](/salt-formulas) isn't the official [saltstack-formulas](/saltstack-formulas) group, which explains my confusion around why this formula had so many non-general features! I figure our contributions are best suited to the official saltstack-formulas group, so I rewrote the formula in a new branch to submit to them, cleaning out any non-general features like reclass meta and the deb pkg and making the formula more applicable to the general Saltstack user-base.

Given that, please feel free to either merge this pull request if you think these changes will be of use to you and your use-case, or to close and reject it if you think it will just clutter your specifically targeted use case. I made your requested changes in case you do think these changes will be applicable to you, but since we don't use reclass I wanted to give you a heads up that I had no way of testing the reclass metadata changes. Please do make sure to test those out and correct any issues if you'll be merging this in.

Thanks again, and best of luck!

**Comment by epcim** [comment]
[**@tmeneau**](https://github.com/tmeneau) commented on [Nov 1, 2017, 7:22 PM GMT+1](https://github.com/salt-formulas/salt-formula-helm/pull/11#issuecomment-341194956 "2017-11-01T18:22:14Z - Replied by Github Reply Comments"):
> I only realized a couple of days ago that [salt-formulas](/salt-formulas) isn't the official [saltstack-formulas](/saltstack-formulas) group, which explains my confusion around why this formula had so many non-general features! I figure our contributions are best suited to the official saltstack-formulas group, so I rewrote the formula in a new branch to submit to them, cleaning out any non-general features like reclass meta and the deb pkg and making the formula more applicable to the general Saltstack user-base.
> 
> Given that, please feel free to either merge this pull request if you think these changes will be of use to you and your use-case, or to close and reject it if you think it will just clutter your specifically targeted use case. I made your requested changes in case you do think these changes will be applicable to you, but since we don't use reclass I wanted to give you a heads up that I had no way of testing the reclass metadata changes. Please do make sure to test those out and correct any issues if you'll be merging this in.
> 
> Thanks again, and best of luck!

Thanks for your contribution anyway. 
This formula is not in the official saltstack-formulas repo, however, we are compatible with "classic". At best both version will have a very similar pillar at the end.

**Pull request closed without merging**
